import type { Algorithm } from '@/features/dsa/dsa-modules/types/algorithm.types';

export const ALGORITHM_CATALOG: Algorithm[] = [
  {
    id: 'bubble-sort',
    name: 'Bubble Sort (Sắp xếp nổi bọt)',
    category: 'Sorting',
    difficulty: 'Easy',
    timeComplexity: 'O(N²)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'quick-sort',
    name: 'Quick Sort (Sắp xếp nhanh)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(log N)',
  },
  {
    id: 'merge-sort',
    name: 'Merge Sort (Sắp xếp trộn)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'heap-sort',
    name: 'Heap Sort (Sắp xếp đống)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'radix-sort',
    name: 'Radix Sort (Sắp xếp theo cơ số)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(d × N)',
    spaceComplexity: 'O(N + k)',
  },
  {
    id: 'counting-sort',
    name: 'Counting Sort (Sắp xếp đếm)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N + K)',
    spaceComplexity: 'O(K)',
  },
  {
    id: 'bucket-sort',
    name: 'Bucket Sort (Sắp xếp theo xô)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N + K)',
    spaceComplexity: 'O(N + K)',
  },
  {
    id: 'linear-search',
    name: 'Linear Search (Tìm kiếm tuần tự)',
    category: 'Searching',
    difficulty: 'Easy',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'binary-search',
    name: 'Binary Search (Tìm kiếm nhị phân)',
    category: 'Searching',
    difficulty: 'Medium',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'sliding-window',
    name: 'Sliding Window (Cửa sổ trượt)',
    category: 'Searching',
    difficulty: 'Medium',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'stack',
    name: 'Stack (Ngăn xếp - LIFO)',
    category: 'Stack-Queue',
    difficulty: 'Easy',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'queue',
    name: 'Queue (Hàng đợi - FIFO)',
    category: 'Stack-Queue',
    difficulty: 'Easy',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'monotonic-stack',
    name: 'Monotonic Stack (Ngăn xếp đơn điệu)',
    category: 'Stack-Queue',
    difficulty: 'Medium',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'bst',
    name: 'Binary Search Tree (Cây BST)',
    category: 'Tree',
    difficulty: 'Medium',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'bfs',
    name: 'Breadth-First Search (Duyệt BFS)',
    category: 'Graph',
    difficulty: 'Medium',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'dfs',
    name: 'Depth-First Search (Duyệt DFS)',
    category: 'Graph',
    difficulty: 'Medium',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'dijkstra',
    name: 'Dijkstra (Đường đi ngắn nhất)',
    category: 'Graph',
    difficulty: 'Hard',
    timeComplexity: 'O((V + E) log V)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'bellman-ford',
    name: 'Bellman-Ford (Đường đi ngắn nhất)',
    category: 'Graph',
    difficulty: 'Hard',
    timeComplexity: 'O(V × E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'kruskal',
    name: 'Kruskal (Cây khung nhỏ nhất)',
    category: 'Graph',
    difficulty: 'Hard',
    timeComplexity: 'O(E log E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'prim',
    name: 'Prim (Cây khung nhỏ nhất)',
    category: 'Graph',
    difficulty: 'Hard',
    timeComplexity: 'O((V + E) log V)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'tarjan',
    name: 'Tarjan (Liên thông mạnh)',
    category: 'Graph',
    difficulty: 'Hard',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'a-star',
    name: 'A* Search (Đường đi tối ưu)',
    category: 'Graph',
    difficulty: 'Hard',
    timeComplexity: 'O(E)',
    spaceComplexity: 'O(V)',
  }
];
