import type { AlgorithmMetadata } from '@/features/dsa/dsa-modules/types/algorithm.types';

export const LOCAL_METADATA: Record<string, AlgorithmMetadata> = {
  'bubble-sort': {
    timeComplexity: 'O(N²)',
    spaceComplexity: 'O(1)',
    description: 'Bubble Sort so sánh các cặp phần tử liền kề và hoán đổi chúng nếu sai thứ tự. Sau mỗi vòng lặp, phần tử lớn nhất "nổi" lên cuối mảng.',
    pseudoCode: ['for i from 0 to N-1', '  for j from 0 to N-i-2', '    if A[j] > A[j+1]', '      swap(A[j], A[j+1])'],
  },
  'quick-sort': {
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(log N)',
    description: 'Quick Sort chọn phần tử chốt (pivot), phân hoạch mảng thành hai nửa: nhỏ hơn và lớn hơn pivot, rồi đệ quy sắp xếp từng nửa.',
    pseudoCode: ['quickSort(A, low, high):', '  if low < high:', '    pi = partition(A, low, high)', '    quickSort(A, low, pi-1)', '    quickSort(A, pi+1, high)'],
  },
  'merge-sort': {
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(N)',
    description: 'Merge Sort chia đôi mảng đệ quy cho đến khi chỉ còn 1 phần tử, rồi gộp (merge) các mảng con đã sắp xếp lại.',
    pseudoCode: ['mergeSort(A, left, right):', '  if left >= right: return', '  mid = (left+right)/2', '  mergeSort(A, left, mid)', '  mergeSort(A, mid+1, right)', '  merge(A, left, mid, right)'],
  },
  'heap-sort': {
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(1)',
    description: 'Heap Sort xây dựng Max-Heap từ mảng, sau đó lần lượt lấy phần tử lớn nhất (root) đặt vào cuối mảng và tái cấu trúc heap.',
    pseudoCode: ['buildMaxHeap(A)', 'for i from N-1 downto 1:', '  swap(A[0], A[i])', '  heapify(A, 0, i)'],
  },
  'radix-sort': {
    timeComplexity: 'O(d × N)',
    spaceComplexity: 'O(N + k)',
    description: 'Radix Sort sắp xếp các phần tử bằng cách xử lý từng chữ số (digit) từ hàng đơn vị đến hàng cao nhất.',
    pseudoCode: ['radixSort(A):', '  for exp = 1; max/exp > 0; exp *= 10:', '    countingSortByDigit(A, exp)'],
  },
  'counting-sort': {
    timeComplexity: 'O(N + K)',
    spaceComplexity: 'O(K)',
    description: 'Counting Sort đếm tần suất xuất hiện của mỗi giá trị, tính tổng cộng dồn (prefix sum), rồi đặt phần tử vào đúng vị trí.',
    pseudoCode: ['count[0..9] = 0', 'for each elem: count[elem%10]++', 'prefix sum', 'build output (right-to-left)'],
  },
  'bucket-sort': {
    timeComplexity: 'O(N + K)',
    spaceComplexity: 'O(N + K)',
    description: 'Bucket Sort phân phối các phần tử vào các xô (bucket) theo phạm vi giá trị, sắp xếp từng xô rồi nối lại.',
    pseudoCode: ['buckets[0..3] = []', 'distribute elements', 'sort each bucket', 'collect'],
  },
  'linear-search': {
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    description:
      'Linear Search duyệt tuần tự từng phần tử trong mảng từ đầu đến cuối để tìm giá trị mục tiêu.',
    pseudoCode: [
      'linearSearch(A, target)',
      '  for i from 0 to N-1',
      '    if A[i] == target',
      '      return i',
      '  return -1',
    ],
  },
  'binary-search': {
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(1)',
    description:
      'Binary Search chia đôi phạm vi tìm kiếm bằng cách so sánh giá trị giữa với target. Yêu cầu mảng đã sắp xếp.',
    pseudoCode: [
      'binarySearch(A, target)',
      '  low = 0, high = N-1',
      '  while low <= high',
      '    mid = (low + high) / 2',
      '    if A[mid] == target: return mid',
      '    else if A[mid] < target: low = mid + 1',
      '    else: high = mid - 1',
    ],
  },
  'sliding-window': {
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
    description:
      'Cửa sổ trượt (Sliding Window) duy trì một phạm vi phần tử liên tiếp (cửa sổ) và di chuyển nó dọc theo mảng để tính toán hiệu quả các bài toán mảng con. Ví dụ này tìm tổng lớn nhất của cửa sổ kích thước K = 3.',
    pseudoCode: [
      'slidingWindow(A, K):',
      '  left = 0, currentSum = 0, maxSum = 0',
      '  for right from 0 to N-1:',
      '    currentSum += A[right]',
      '    if right - left + 1 > K:',
      '      currentSum -= A[left]',
      '      left++',
      '    maxSum = max(maxSum, currentSum)',
      '  return maxSum',
    ],
  },
  stack: {
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
    description:
      'Ngăn xếp (Stack) hoạt động theo nguyên tắc LIFO — Vào sau ra trước. Push đẩy vào đỉnh, Pop lấy ở đỉnh ra.',
    pseudoCode: [
      'stack = []',
      'push(value):',
      '  stack.append(value)',
      'pop():',
      '  return stack.removeLast()',
    ],
  },
  queue: {
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
    description:
      'Hàng đợi (Queue) hoạt động theo nguyên tắc FIFO — Vào trước ra trước. Enqueue thêm vào cuối, Dequeue lấy ở đầu.',
    pseudoCode: [
      'queue = []',
      'enqueue(value):',
      '  queue.append(value)',
      'dequeue():',
      '  return queue.removeFirst()',
    ],
  },
  'monotonic-stack': {
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
    description:
      'Ngăn xếp đơn điệu (Monotonic Stack) duy trì các phần tử tăng dần hoặc giảm dần để giải quyết hiệu quả các bài toán như "Tìm phần tử lớn hơn tiếp theo" (Next Greater Element) trong thời gian tuyến tính O(N).',
    pseudoCode: [
      'nextGreaterElement(A):',
      '  stack = []',
      '  res = [-1 for _ in A]',
      '  for i from 0 to N-1:',
      '    while stack is not empty and A[stack.top()] < A[i]:',
      '      idx = stack.pop()',
      '      res[idx] = A[i]',
      '    stack.push(i)',
      '  return res',
    ],
  },
  bst: {
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(N)',
    description:
      'Cây tìm kiếm nhị phân (BST) lưu trữ dữ liệu sao cho node trái nhỏ hơn, node phải lớn hơn node cha.',
    pseudoCode: [
      'insert(root, value):',
      '  if root is null: return new Node(value)',
      '  if value < root.value:',
      '    root.left = insert(root.left, value)',
      '  else:',
      '    root.right = insert(root.right, value)',
      '  return root',
    ],
  },
  bfs: {
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description:
      'Duyệt theo chiều rộng (BFS) đi qua các đỉnh của đồ thị/cây theo từng lớp (chiều rộng). Sử dụng Hàng đợi (Queue) để điều phối thứ tự duyệt.',
    pseudoCode: [
      'BFS(root):',
      '  queue = [root]',
      '  visited = {root}',
      '  while queue is not empty:',
      '    curr = queue.dequeue()',
      '    for neighbor in curr.neighbors:',
      '      if neighbor not in visited:',
      '        visited.add(neighbor)',
      '        queue.enqueue(neighbor)',
    ],
  },
  dfs: {
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description:
      'Duyệt theo chiều sâu (DFS) bắt đầu từ gốc, đi sâu hết mức có thể dọc theo mỗi nhánh trước khi quay lui (backtrack). Sử dụng Ngăn xếp (Stack) hoặc Đệ quy.',
    pseudoCode: [
      'DFS(node, visited):',
      '  visited.add(node)',
      '  for neighbor in node.neighbors:',
      '    if neighbor not in visited:',
      '      DFS(neighbor, visited)',
    ],
  },
  dijkstra: {
    timeComplexity: 'O((V + E) log V)',
    spaceComplexity: 'O(V)',
    description:
      'Thuật toán Dijkstra tìm đường đi ngắn nhất từ đỉnh nguồn đến tất cả các đỉnh khác trên đồ thị có trọng số không âm. Thuật toán sử dụng Hàng đợi ưu tiên (Priority Queue) để chọn đỉnh gần nhất tại mỗi bước.',
    pseudoCode: [
      'Dijkstra(graph, source):',
      '  dist = {v: infinity for v in graph}',
      '  dist[source] = 0',
      '  pq = PriorityQueue(source, 0)',
      '  while pq is not empty:',
      '    curr, d = pq.popMin()',
      '    for neighbor, weight in curr.edges:',
      '      newDist = d + weight',
      '      if newDist < dist[neighbor]:',
      '        dist[neighbor] = newDist',
      '        pq.push(neighbor, newDist)',
    ],
  },
  'bellman-ford': {
    timeComplexity: 'O(V × E)',
    spaceComplexity: 'O(V)',
    description:
      'Thuật toán Bellman-Ford tìm đường đi ngắn nhất từ một đỉnh nguồn đến mọi đỉnh khác. Điểm mạnh của nó là xử lý được đồ thị có trọng số âm và có khả năng phát hiện chu trình âm (Negative Cycle).',
    pseudoCode: [
      'BellmanFord(graph, source):',
      '  dist = {v: infinity for v in graph}',
      '  dist[source] = 0',
      '  for i from 1 to V-1:',
      '    for each edge (u, v, weight) in graph:',
      '      if dist[u] + weight < dist[v]:',
      '        dist[v] = dist[u] + weight',
      '  for each edge (u, v, weight) in graph:',
      '    if dist[u] + weight < dist[v]:',
      '      return "Graph contains negative weight cycle"',
    ],
  },
  'kruskal': {
    timeComplexity: 'O(E log E)',
    spaceComplexity: 'O(V)',
    description:
      'Thuật toán Kruskal tìm Cây khung nhỏ nhất (Minimum Spanning Tree) của đồ thị vô hướng có trọng số. Nó sắp xếp các cạnh theo trọng số tăng dần và thêm dần vào cây bằng cấu trúc Disjoint Set (Union-Find) để tránh tạo chu trình.',
    pseudoCode: [
      'Kruskal(graph):',
      '  MST = []',
      '  edges = sort(graph.edges, by=weight)',
      '  uf = UnionFind(graph.nodes)',
      '  for edge(u, v, weight) in edges:',
      '    if uf.find(u) != uf.find(v):',
      '      uf.union(u, v)',
      '      MST.append(edge)',
      '      if MST.size == V-1: break',
      '  return MST',
    ],
  },
  'prim': {
    timeComplexity: 'O((V + E) log V)',
    spaceComplexity: 'O(V)',
    description:
      'Thuật toán Prim tìm Cây khung nhỏ nhất bằng cách bắt đầu từ một đỉnh bất kỳ, liên tục mở rộng cây bằng cách chọn cạnh có trọng số nhỏ nhất nối một đỉnh trong cây với một đỉnh ngoài cây (dùng Priority Queue).',
    pseudoCode: [
      'Prim(graph):',
      '  MST = []',
      '  visited = {start_node}',
      '  pq = PriorityQueue(edges_from_start)',
      '  while pq is not empty and visited.size < V:',
      '    edge(u, v, weight) = pq.popMin()',
      '    if v in visited: continue',
      '    visited.add(v)',
      '    MST.append(edge)',
      '    for next_edge in v.edges:',
      '      pq.push(next_edge)',
      '  return MST',
    ],
  },
  'tarjan': {
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    description:
      'Thuật toán Tarjan tìm các thành phần liên thông mạnh (Strongly Connected Components - SCC) trong đồ thị có hướng chỉ với một lần duyệt DFS. Bằng cách gán chỉ số (low-link value), nó xác định các cụm đỉnh có thể đi tới lẫn nhau.',
    pseudoCode: [
      'TarjanDFS(u):',
      '  idx[u] = low[u] = ++timer',
      '  stack.push(u), onStack[u] = true',
      '  for v in graph[u]:',
      '    if idx[v] is unvisited:',
      '      TarjanDFS(v)',
      '      low[u] = min(low[u], low[v])',
      '    else if onStack[v]:',
      '      low[u] = min(low[u], idx[v])',
      '  if low[u] == idx[u]:',
      '    SCC = []',
      '    do {',
      '      w = stack.pop(), onStack[w] = false',
      '      SCC.append(w)',
      '    } while (w != u)',
    ],
  },
  'a-star': {
    timeComplexity: 'O(E)',
    spaceComplexity: 'O(V)',
    description:
      'A* (A-Star) là thuật toán tìm đường đi tối ưu thông minh. Nó cải tiến Dijkstra bằng cách sử dụng hàm Heuristic h(n) để ước lượng chi phí còn lại từ đỉnh hiện tại đến đích, giúp tìm đường nhanh hơn rất nhiều trong không gian lớn (như bản đồ game).',
    pseudoCode: [
      'AStar(graph, start, goal):',
      '  openSet = PriorityQueue()',
      '  openSet.push(start, f=0)',
      '  gScore[start] = 0',
      '  while openSet is not empty:',
      '    current = openSet.popMin()',
      '    if current == goal: return reconstructPath()',
      '    for neighbor in current.neighbors:',
      '      tentative_g = gScore[current] + weight(current, neighbor)',
      '      if tentative_g < gScore[neighbor]:',
      '        gScore[neighbor] = tentative_g',
      '        fScore = tentative_g + heuristic(neighbor, goal)',
      '        openSet.push(neighbor, fScore)',
    ],
  },
};
